# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='tipo',
            new_name='buro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cuota',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefonica',
            field=models.BooleanField(default=True),
        ),
    ]
