# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0002_auto_20171109_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='cedula',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='buro',
            field=models.BooleanField(choices=[(True, 'S\xed'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel1',
            field=models.IntegerField(verbose_name='Ingrese Tel 1'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefonica',
            field=models.BooleanField(choices=[(True, 'S\xed'), (False, 'No')]),
        ),
    ]
