# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0003_auto_20171201_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('pasaporte', 'Pasaporte'), ('cedula_identidad', 'C\xe9dula de Identidad'), ('cedula_residente', 'C\xe9dula de Residente')], default='cedula_identidad', max_length=50, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=50, verbose_name='N\xfamero de Documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel1',
            field=models.IntegerField(verbose_name='N\xfamero de Tel\xe9fono 1'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel2',
            field=models.IntegerField(verbose_name='N\xfamero de Tel\xe9fono 2'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel3',
            field=models.IntegerField(verbose_name='N\xfamero de Tel\xe9fono 3'),
        ),
    ]
